### ISSUE TITLE
When jump to tiktok app for authorized login, it will show the error: "In order to protect our community, we restrict certain content on our platform."

### ISSUE THREAD

**Issue by sunny635533** [tiktok/tiktok-opensdk-ios#11]
On some ios devices, the following error will appear when you jump from the My app page to the tiktok app for authorized login：
![image](https://github.com/tiktok/tiktok-opensdk-ios/assets/4737071/5519f4f1-ea8f-435d-adc6-f2b5ab218118)

This sentence means: "In order to protect our community, we restrict certain content on our platform."

"https://m.iboomingglobal.com/app/?code=xxxx" , it is my [universal link](https://developer.apple.com/documentation/xcode/allowing-apps-and-websites-to-link-to-your-content?language=objc).

So I don't know why some users have this problem with their mobile phones.If you konw,please tell me, Thanks.

**Comment by sunny635533** [comment]
@nickdnk Hello, I encountered a problem, but no one has responded yet.  I'm sorry to send you a message.About this issue,if you know please help me.Thank you.

**Comment by stephen-boyle** [comment]
Hi @sunny635533 , apologies for the late reply. I will take a look at what could be causing this. You mentioned that this occurs on some iOS devices: do you mean different iOS versions or specific types of iPhones? If you can provide what iOS version and iPhone type this occurs on, I will try and reproduce the issue.

**Comment by nickdnk** [comment]
> @nickdnk Hello, I encountered a problem, but no one has responded yet. I'm sorry to send you a message.About this issue,if you know please help me.Thank you.

Hey. I don't have anything to do with this. Please don't tag me :)

**Comment by stephen-boyle** [comment]
@sunny635533 thanks for the video, it helps me understand the problem better! I will get back to you after some investigating

**Comment by stephen-boyle** [comment]
@sunny635533 I believe the issue should be resolved, can you confirm that this isn't happening anymore?

**Comment by sunny635533** [comment]
@stephen-boyle Thank you for solving the problem. I will confirm with the user whether this problem still exists and then reply to you.
