### ISSUE TITLE
error_code=-4

### ISSUE THREAD

**Issue by wangqianjun** [tiktok/tiktok-opensdk-ios#12]
When I use the sharing feature, I get the following error. Please help me resolve it. Thank you.
 
`https://www.xxx.com/applinks/?from_platform=tiktoksharesdk&request_id=4517E659-083C-43AB-8F9A-DB63D09D6172&error_code=-4&error_description=Permissions%20denied&share_state=20003&response_id=A1013649-A297-4D14-8A7E-58EF29D7343C`

**Comment by stephen-boyle** [comment]
From the error code and description, it looks like you probably did not add Login Kit and Share Kit on your developer account. Please make sure you have added them. If you haven't yet, you can do this by going to the [TikTok for Developers website](https://developers.tiktok.com/), navigating to the Manage apps page, and clicking + Add products on your app configuration page.
![download](https://github.com/tiktok/tiktok-opensdk-ios/assets/115671823/b0a73684-9e6b-4e38-828f-58a873259faf)

**Comment by stephen-boyle** [comment]
Hi @wangqianjun , just wanted to follow up on whether this was able to resolve your issue?
