### ISSUE TITLE
ShareKit - TikTok opens and closes immediately without sharing media

### ISSUE THREAD

**Issue by Priyankkjain** [tiktok/tiktok-opensdk-ios#22]
Hi, I am using TikTok's iOS SDK Share Kit to share my content from my app to TikTok. When I share a picture the application opens, showing a loading and immediately closing. I am not getting any response in return to identify the issue. This is the code I am using to share with TikTok. I have also attached a video to give you an idea about the issue. 

https://github.com/tiktok/tiktok-opensdk-ios/assets/20212314/3bc8d2be-566e-4a1a-8c82-019cbbce1bed

```
let shareRequest = TikTokShareRequest(localIdentifiers: [videoFile!], mediaType: fileType == "image" ? .image : .video, redirectURI: redirectUrl!)
        shareRequest.shareFormat = .normal
        DispatchQueue.main.async {
            let returnResult = shareRequest.send { response in
                guard let shareResponse = response as? TikTokShareResponse else { return }
                    if shareResponse.errorCode == .noError {
                        print("Share succeeded!")
                        result("success")
                    } else {
                        print("Share Failed! Error Code: \(shareResponse.errorCode.rawValue) Error Message: \(shareResponse.errorDescription ?? "") Share State: \(shareResponse.shareState)")
                        result("error")
                    }
            }
            print("the result \(returnResult)")
        }
```

**Comment by arteevraina** [comment]
Hey @Priyankkjain ,
If don't mind, would you share the steps that you used to run tiktok inside iOS device for testing purposes. I tried with VPN but it failed.

**Comment by arteevraina** [comment]
Hey @Priyankkjain , I am also facing the same issue as described above. 
Were you able to figure this out ? 
I am considering to downgrade the SDK and use older functions as I read somewhere that they seemed to work but this version (``2.2.0``) doesn't.

**Comment by arteevraina** [comment]
Well, It was not a version issue. I had to convert the path to ``PHAsset`` and then share it to Tiktok and then it worked.

**Comment by stephen-boyle** [comment]
@Priyankkjain @arteevraina  If you are not receiving a response when it returns to your app, it may be because you haven't updated your App Delegate and/or Scene Delegate. Please take a look at the README file again and make sure you have followed each step, especially the step regarding the App/Scene Delegate

Lastly, if it is returning an error right away, it may be because you have not configured Share Kit on the developer portal. Check out this [issue]([error_code=-4 · Issue #12 · tiktok/tiktok-opensdk-ios](https://github.com/tiktok/tiktok-opensdk-ios/issues/12)) to find out how to add Share Kit on the developer portal

**Comment by arteevraina** [comment]
> @Priyankkjain @arteevraina If you are not receiving a response when it returns to your app, it may be because you haven't updated your App Delegate and/or Scene Delegate. Please take a look at the README file again and make sure you have followed each step, especially the step regarding the App/Scene Delegate
> 
> Lastly, if it is returning an error right away, it may be because you have not configured Share Kit on the developer portal. Check out this [issue]([error_code=-4 · Issue #12 · tiktok/tiktok-opensdk-ios](https://github.com/tiktok/tiktok-opensdk-ios/issues/12)) to find out how to add Share Kit on the developer portal

Thanks for the reply @stephen-boyle . But, I had done all the things that were mentioned in your comment and also in the documentation. 

As I said in my previous reply, it was issue related to me directly sharing the path in the send request instead of converting it to PHAsset. I had to figure that out myself since I could not find that in the documentation. As a feedback, you can consider updating the documentation with the necessary changes making sure that the end user of the package knows which operations they need to perform before proceeding to share to Tiktok. 👍

**Comment by Priyankkjain** [comment]
Thanks for the information regarding this @arteevraina. I think my issue is also the same. I am directly passing the path to request. I will try to convert it to PHAsset and will see.

**Comment by ankit01217** [comment]
@arteevraina I am seeing a similar issue. I have set up app delegate calls as in docs and also using PHAsset identifiers for share request, but still getting back permissions denied. Is there anything else that can cause this error?

request_id=9D029E1A-576D-48C0-8B3B-C6EFD7553AED&error_code=-4&error_description=Permissions%20denied&share_state=20003

**Comment by arteevraina** [comment]
> @arteevraina I am seeing a similar issue. I have set up app delegate calls as in docs and also using PHAsset identifiers for share request, but still getting back permissions denied. Is there anything else that can cause this error?

@ankit01217 Not sure though, but I think your app needs to have photo library permission in order to share to Tiktok.

**Comment by MateusHBR** [comment]
I'm facing the same issue here

```
Deep Link does not contain valid required params
    "error_code" = "-4";
    "error_string" = "Permissions denied";
    "from_platform" = tiktoksharesdk;
    "request_id" = "82F4BA10-EB72-4C78-AA0A-C7C744910ED0";
    "response_id" = "A1EB62C4-49EA-4FBC-B9E5-1DC8F4FCB377";
    "share_state" = 20003;
```

**Comment by adamvnovak** [comment]
Same issue here, error code of -4 but photo library permissions exist and I'm passing a PHAsset identifier to the ShareRequest...

**Comment by stephen-boyle** [comment]
@Priyankkjain @adamvnovak @ankit01217 @khandakerTR @arteevraina @MateusHBR Hello everyone, we discovered the cause of this issue and have fixed it. To resolve the issue, go to your app page and click the "Submit for review" button.

![20240228-125140](https://github.com/tiktok/tiktok-opensdk-ios/assets/115671823/af2e6f47-3d0b-4d4b-98fa-ef4a3699d96e)

**Comment by beforeold** [comment]
Same issue here, error code of -4 but photo library permissions exist and I'm passing a PHAsset identifier to the ShareRequest...

and the Share Kit product is added and approved, 😭

**Comment by GemperC** [comment]
did anyone found a solution to this? i have tried all of the above

**Comment by beforeold** [comment]
> did anyone found a solution to this? i have tried all of the above

resubkit with any other tiktok product solved my issue

**Comment by GemperC** [comment]
> > did anyone found a solution to this? i have tried all of the above
> 
> resubmitting with any other tiktok product solved my issue

i am using only the share sdk, you are saying that i should activate another product and submit with it? what another product did you activate?

**Comment by beforeold** [comment]
> > > did anyone found a solution to this? i have tried all of the above
> > 
> > 
> > resubmitting with any other tiktok product solved my issue
> 
> i am using only the share sdk, you are saying that i should activate another product and submit with it? what another product did you activate?
> 
> did you need to setup ios and andorid in their dashboard (appstore and play store links)?

submitted Login Service

yes, the App Store link is setup
