### ISSUE TITLE
[Feature]: Support App Privacy Manifest

### ISSUE THREAD

**Issue by sylvia-tencent-wmt** [tiktok/tiktok-opensdk-ios#24]
Aims
At WWDC23, Apple introduced a new Privacy Manifest and signatures for SDKs.
I would like to know when you plan to adopt these changes, considering Apple's deadline in Spring 2024.

References:

- [Apple Developer News](https://developer.apple.com/news/?id=r1henawx)
- [Third-party SDK Requirements](https://developer.apple.com/support/third-party-SDK-requirements/)
- [Describing Use of Required Reason API](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api)

Could you please provide information on your adoption timeline for these updates? Thank you.

Description/Implementation Details

- Add Privacy Manifest
- Describing the use of required reason API

**Comment by GuidoPu** [comment]
Hi there,

Thank you for bringing this to our attention. I'm pleased to inform you that the Privacy Manifest file has been added to the repository as of the latest release. You can find the file in the project directory.
