### ISSUE TITLE
Login Kit TikTokAuthRequest.send completion not call

### ISSUE THREAD

**Issue by yuximin** [tiktok/tiktok-opensdk-ios#25]
I have implemented the TikTok login function according to the document, and have successfully activated TikTok authorization and return to our app. But it did not callback to the `completion` in `TikTokAuthRequest.send`. It only got the URL in `func application(_ application: UIApplication, continue userActivity: NSUserActivity, restorationHandler: @escaping ([UIUserActivityRestoring]?) -> Void) -> Bool`. What should I do to obtain a callback in `TikTokAuthRequest.send`‘s completion. Hope your answer.

**Comment by Heski99** [comment]
> لقد قمت بتنفيذ وظيفة تسجيل الدخول إلى TikTok وفقًا للمستند، وقمت بتنشيط ترخيص TikTok بنجاح والعودة إلى تطبيقنا. لكنه لم يتم رد الاتصال بـ `completion`in `TikTokAuthRequest.send`. لقد حصل فقط على عنوان URL بتنسيق `func application(_ application: UIApplication, continue userActivity: NSUserActivity, restorationHandler: @escaping ([UIUserActivityRestoring]?) -> Void) -> Bool`. ماذا علي أن أفعل للحصول على رد اتصال عند `TikTokAuthRequest.send`اكتمال . نأمل إجابتك.

Thanks
