### ISSUE TITLE
Could not find module 'TikTokOpenSDKCore' for target 'x86_64-apple-ios-simulator'; found: arm64-apple-ios-simulator

### ISSUE THREAD

**Issue by erenincesu-appnation** [tiktok/tiktok-opensdk-ios#78]
**Steps the produce**

When I try to run my Flutter app on the simulator, it gives an error.

**Expected results**

App works on simulator normally

**Actual results**

App doesnt work on ios simulator and gives an error : Could not find module 'TikTokOpenSDKCore' for target 'x86_64-apple-ios-simulator'; found: arm64-apple-ios-simulator

Environment:

[✓] Flutter (Channel stable, 3.22.2, on macOS 14.4.1 23E224 darwin-arm64, locale en-TR)
    • Flutter version 3.22.2 on channel stable at /Users/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (6 months ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.16.2

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

Simulator : Iphone 15 Pro Max - ios 17.5

**Comment by spapapet** [comment]
@erenincesu Hey!
Did you manage to find a solution or something? I'm stuck too

**Comment by erenincesu-appnation** [comment]
Hello @spapapet,

I removed the package and then just installed the pod. My problem was solved.

I hope it helps to solve.

**Comment by spapapet** [comment]
@erenincesu so you removed the package from Xcode and left the pod in podfile?

**Comment by erenincesu-appnation** [comment]
@spapapet  Yeah, that's all I do. now i can run normally

**Comment by spapapet** [comment]
It did not work for me. What device do you use? I am on Apple silicon with iOS simulator

**Comment by spapapet** [comment]
@erenincesu
